apiVersion: v1
kind: Service
metadata:
  name: my-chatbot-service
spec:
  selector:
    app: my-chatbot-pod
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3050
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: my-chatbot-pod
  labels:
    app: my-chatbot-pod
spec:
  containers:
  - name: my-chatbot-container
    image: narendersurabhi/my-chatbot:latest
    ports:
    - containerPort: 3050

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 3051
      targetPort: 3050
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  labels:
    app: chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: narendersurabhi/my-chatbot:latest
        ports:
        - containerPort: 3050
        env: 
        - name: APP_TITLE
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.name
